hparams:
  _target_: monai.networks.nets.UNet
  in_channels: ${dataset.img_channels}
  out_channels: ${dataset.num_classes}
  spatial_dims: ${dataset.img_dim}
  dropout: 0
  channels: [16, 32, 64, 128, 256]
  strides: [2, 2, 2, 2]
  num_res_units: 2
  norm: instance
checkpoint: null
