# @package _global_

defaults:
  - override /trainer: cpu

csf_aggregation:
  hparams:
    _target_: segmentation_failures.models.confidence_aggregation.RadiomicsAggregationModule
    regression_model: regression_forest
    dataset_id: ${dataset.dataset_id}
    target_metrics: null # inferred automatically
    image_dim: ${dataset.img_dim}
    confid_name: ???
    confid_threshold: null # if not set/null, this will be computed on the validation set as in Jungo et al.
  trainable: true
  checkpoint: null
  twostage: true

trainer:
  max_epochs: 1
  check_val_every_n_epoch: 1

callbacks:
  train:
    model_checkpoint:
      save_top_k: 0
