_target_: pytorch_lightning.Trainer

accelerator: gpu
devices: 1

min_epochs: 1
max_epochs: 10
precision: 16-mixed

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0
log_every_n_steps: 20
check_val_every_n_epoch: 1
# # for full reproducibility, set this to true; default is false
# deterministic: false
