hparams:
  _target_: segmentation_failures.models.pixel_confidence.PosthocMultiConfidenceSegmenter
  csf_names:
    - maxsoftmax
    - predictive_entropy
  num_mcd_samples: 0
  overlapping_classes: ${dataset.overlapping_classes}
  everything_on_gpu: false
trainable: false
checkpoint: null
