hparams:
  _target_: segmentation_failures.models.pixel_confidence.PosthocMultiConfidenceSegmenter
  csf_names:
    # - maxsoftmax
    - predictive_entropy
    - mutual_information
  num_mcd_samples: 10
  overlapping_classes: ${dataset.overlapping_classes}
  everything_on_gpu: false
trainable: false
checkpoint: null
